import { IThingDocument } from './thing';

export interface ICreativeWorkDocument extends IThingDocument {
  about: unknown;
  // abstract: string;
  // accessMode: string;
  // accessModeSufficient: string[];
  // accessibilityAPI: string;
  // accessibilityControl: string;
  // accessibilityFeature: string;
  // accessibilityHazard: string;
  // accessibilitySummary: string;
  // accountablePerson: string;
  // acquireLicensePage: string;
  aggregateRating: number;
  alternativeHeadline: string;
  // assesses: string;
  // associatedMedia: string;
  // audience: string;
  // audio: string;
  authors: unknown; // any[]; // developers
  awards: string[];
  character: unknown;
  // citation: string;
  comments: string[];
  // commentsCount: number;
  // conditionsOfAccess: string;
  // contentLocation: string;
  // contentRating: string;
  // contentReferenceTime: Date;
  // contributors: string[];
  // copyrightHolder: any;
  // copyrightNotice: string;
  // copyrightYear: number;
  // correction: string;
  // creativeWorkStatus: string;
  // creditText: string;
  dateCreated: Date;
  dateModified: Date;
  datePublished: Date;
  // discussionUrl: string;
  // editEIDR: string;
  // editor: any;
  // educationalAlignment: string;
  // educationalLevel: string;
  // educationalUse: string;
  // encodingFormat: string;
  // exampleOfWork: any;
  // expires: Date;
  // funder: any;
  genres: string[];
  // hasPart: any;
  // headline: string;
  inLanguage: string[];
  // interactionStatistic: number;
  // interactivityType: string;
  free: boolean;
  // isBasedOn: any;
  // isFamilyFriendly: boolean;
  // isPartOf: any;
  keywords: string[];
  // learningResourceType: string;
  // license: string;
  // locationCreated: string;
  mainEntity: unknown; // any;
  // maintainer: any;
  // material: string;
  // materialExtent: string;
  // mentions: any;
  // offers: any;
  // pattern: string;
  position: number | string;
  // producer: any;
  // provider: any;
  // publication: any;
  publisher: unknown; // any;
  // publisherImprint: any;
  // publishingPrinciples: string;
  // recordedAt: any;
  // releasedEvent: any;
  reviews: string[];
  // schemaVersion: string;
  // sdDatePublished: Date;
  // sdLicense: string;
  // sdPublisher: string;
  size: string;
  // sourceOrganization: string;
  // spatial: any;
  // spatialCoverage: any;
  // sponsor: any;
  // teaches: string;
  temporalCoverage: string;
  // text: string;
  // thumbnailUrl: string;
  // timeRequired: number;
  // isTranslationOfWork: ICreativeWorkDocument;
  // translator: any;
  // typicalAgeRange: string;
  // usageInfo: string;
  version: number | string;
  // video: any;
  // workExample: ICreativeWorkDocument[];

  // workTranslations: ICreativeWorkDocument[];
}
